### ISSUE TITLE
Error "No command was given" 

### ISSUE THREAD

**Issue by thuanpv** [guidovranken/fuzzing-corpora-directory#3]
Thanks @guidovranken for creating and sharing this really cool resource!

I have tried to use the get.py script to download some corpora. Somehow it did not work. I got the following error message after running "get.py png in-png"

```
No command was given.

Choose one of -b, -d, -e, or -r to do something.
Try `/usr/bin/gsutil --help' for more information.
Archive:  /tmp/tmpk5mka_6_
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/tmpk5mka_6_ or
        /tmp/tmpk5mka_6_.zip, and cannot find /tmp/tmpk5mka_6_.ZIP, period.
Traceback (most recent call last):
  File "get.py", line 224, in <module>
    corpus.unpacker().unpack(corpus.getter(), output_directory)
  File "get.py", line 143, in unpack
    subprocess.run(args, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['unzip', '-o', '/tmp/tmpk5mka_6_', '-d', 'in-png']' returned non-zero exit status 9.
```

The same issue happened for wasm corpus format.

**Comment by thuanpv** [comment]
It seems to me this is a format-specific issue. The get.py scripts works well with the icc format.

**Comment by guidovranken** [comment]
Hi @thuanpv , someone I missed this issue.

You have the wrong gsutils installed: https://stackoverflow.com/questions/7989741/how-to-configure-gsutil

Remove the distribution package gsutil and install https://cloud.google.com/storage/docs/gsutil_install

**Comment by thuanpv** [comment]
Thanks @guidovranken. So I close this issue.
